INSERT INTO venues (venue_name, location)
VALUES ('The Grand Theater', 'New York, NY'),
       ('Sunset Arena', 'Los Angeles, CA'),
       ('Riverfront Stadium', 'Chicago, IL'),
       ('Golden Gate Pavilion', 'San Francisco, CA'),
       ('Liberty Hall', 'Boston, MA'),
       ('Starlight Venue', 'Seattle, WA'),
       ('Central Park Amphitheater', 'New York, NY'),
       ('Hollywood Bowl', 'Los Angeles, CA'),
       ('Windy City Center', 'Chicago, IL'),
       ('Bay Area Coliseum', 'Oakland, CA'),
       ('Freedom Plaza', 'Washington, DC'),
       ('Lakeside Arena', 'Minneapolis, MN'),
       ('Desert Sun Stadium', 'Phoenix, AZ'),
       ('Mile High Venue', 'Denver, CO'),
       ('Oceanfront Pavilion', 'Miami, FL'),
       ('Historic Music Hall', 'Nashville, TN'),
       ('Texas Star Arena', 'Austin, TX'),
       ('Emerald City Theater', 'Seattle, WA'),
       ('Garden State Center', 'Newark, NJ'),
       ('Sunshine Stadium', 'Orlando, FL'),
       ('Rocky Mountain Hall', 'Boulder, CO'),
       ('Pacific Coast Arena', 'Portland, OR'),
       ('Midwest Event Center', 'St. Louis, MO'),
       ('Southern Lights Venue', 'Atlanta, GA'),
       ('Northern Star Pavilion', 'Boston, MA');


INSERT INTO attendees (attendee_name, email)
VALUES ('John Smith', 'john.smith@email.com'),
       ('Sarah Johnson', 'sarah.j@email.com'),
       ('Michael Brown', 'michael.brown@email.com'),
       ('Emily Davis', 'emily.davis@email.com'),
       ('William Taylor', 'will.taylor@email.com'),
       ('Lisa Anderson', 'lisa.a@email.com'),
       ('David Wilson', 'david.wilson@email.com'),
       ('Jennifer Lee', 'jen.lee@email.com'),
       ('Robert Martinez', 'robert.m@email.com'),
       ('Michelle Chen', 'michelle.chen@email.com'),
       ('Thomas White', 'tom.white@email.com'),
       ('Kelly Thompson', 'kelly.t@email.com'),
       ('James Garcia', 'james.g@email.com'),
       ('Patricia Miller', 'pat.miller@email.com'),
       ('Christopher Clark', 'chris.clark@email.com'),
       ('Amanda Rodriguez', 'amanda.r@email.com'),
       ('Daniel Kim', 'daniel.kim@email.com'),
       ('Elizabeth Parker', 'liz.parker@email.com'),
       ('Matthew Turner', 'matt.turner@email.com'),
       ('Rachel Phillips', 'rachel.p@email.com'),
       ('Andrew Walker', 'andrew.w@email.com'),
       ('Stephanie Hall', 'steph.hall@email.com'),
       ('Brian Young', 'brian.y@email.com'),
       ('Nicole Adams', 'nicole.adams@email.com'),
       ('Kevin Scott', 'kevin.scott@email.com');

INSERT INTO events (event_name, event_date, venue_id)
VALUES ('Summer Music Festival', '2023-06-15', 1),
       ('Tech Conference 2023', '2023-07-20', 2),
       ('Food & Wine Expo', '2023-08-12', 3),
       ('Marathon Race', '2023-09-10', 4),
       ('Art Gallery Opening', '2023-10-05', 5),
       ('Winter Jazz Night', '2023-11-18', 6),
       ('New Year Countdown', '2023-12-31', 7),
       ('Business Leadership Summit', '2024-01-15', 8),
       ('Valentine''s Concert', '2024-02-14', 9),
       ('Spring Flower Show', '2024-03-22', 10),
       ('Film Premiere', '2024-04-05', 11),
       ('Science Fair', '2024-05-18', 12),
       ('Beach Volleyball Tournament', '2024-06-08', 13),
       ('Independence Day Fireworks', '2024-07-04', 14),
       ('Comedy Night', '2024-08-16', 15),
       ('Book Reading Session', '2024-09-07', 16),
       ('Halloween Party', '2024-10-31', 17),
       ('Charity Gala Dinner', '2024-11-22', 18),
       ('Christmas Market', '2024-12-15', 19),
       ('Startup Pitch Competition', '2023-06-28', 20),
       ('Yoga Retreat', '2023-07-30', 21),
       ('Photography Workshop', '2023-09-14', 22),
       ('Poetry Slam', '2023-10-21', 23),
       ('Cooking Masterclass', '2023-11-05', 24),
       ('Dance Performance', '2023-12-10', 25);

INSERT INTO event_attendee (event_id, attendee_id)
VALUES (1, 5),
       (1, 10),
       (2, 3),
       (2, 7),
       (3, 12),
       (3, 18),
       (4, 6),
       (4, 20),
       (5, 9),
       (5, 15),
       (6, 2),
       (6, 14),
       (7, 11),
       (7, 23),
       (8, 4),
       (8, 21),
       (9, 1),
       (9, 19),
       (10, 8),
       (10, 22),
       (11, 13),
       (12, 16),
       (13, 17),
       (14, 24),
       (15, 25);